{
 "title": "Iot_TRAP_09/06/2021_12:22:50",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "250ms",
 "panels": [
  { "title": "Total statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "total_tx_done",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "measurement": "tot_tx_done",
     "select": [
      [
       { "params": [ "tot_tx_done" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "total_rx_done",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "measurement": "tot_rx_done",
     "select": [
      [
       { "params": [ "tot_rx_done" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "total_tx_wait",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "measurement": "tot_tx_wait",
     "select": [
      [
       { "params": [ "tot_tx_wait" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "total_rx_fail",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "measurement": "tot_rx_fail",
     "select": [
      [
       { "params": [ "tot_rx_fail" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "total_burst",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "measurement": "tot_burst",
     "select": [
      [
       { "params": [ "tot_burst" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "tot_dbg",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "measurement": "tot_dbg",
     "select": [
      [
       { "params": [ "tot_dbg" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "Device_0", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Energy level [%]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "engy",
     "query": "SELECT mean(\"value\") FROM \"engy\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "engy_0" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "tx_done",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "measurement": "tx_done",
     "select": [
      [
       { "params": [ "tx_done_0" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "rx_done",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "measurement": "rx_done",
     "select": [
      [
       { "params": [ "rx_done_0" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "tx_wait",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "measurement": "tx_wait",
     "select": [
      [
       { "params": [ "tx_wait_0" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "rx_fail",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "measurement": "rx_fail",
     "select": [
      [
       { "params": [ "rx_fail_0" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "burst",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "measurement": "burst",
     "select": [
      [
       { "params": [ "burst_0" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "dbg",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "measurement": "dbg",
     "select": [
      [
       { "params": [ "dbg_0" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "Device_1", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Energy level [%]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "engy",
     "query": "SELECT mean(\"value\") FROM \"engy\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "engy_1" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "tx_done",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "measurement": "tx_done",
     "select": [
      [
       { "params": [ "tx_done_1" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "rx_done",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "measurement": "rx_done",
     "select": [
      [
       { "params": [ "rx_done_1" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "tx_wait",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "measurement": "tx_wait",
     "select": [
      [
       { "params": [ "tx_wait_1" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "rx_fail",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "measurement": "rx_fail",
     "select": [
      [
       { "params": [ "rx_fail_1" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "burst",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "measurement": "burst",
     "select": [
      [
       { "params": [ "burst_1" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "dbg",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "measurement": "dbg",
     "select": [
      [
       { "params": [ "dbg_1" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}